name = "project-eden-online"
compatibility_date = "2026-09-30"

routes = [
  { pattern = "project-eden.online", custom_domain = true },
  { pattern = "www.project-eden.online", custom_domain = true },
]

[assets]
directory = "./dist"
# Serve index.html for client-side routes like /profile
not_found_handling = "single-page-application"
